import type { Situacion } from "../../schema"

// Verano · tipo personaje. Fuente: docs/03-banco-verano.md
export const situacionesVeranoPersonaje: Situacion[] = [
  {
    id: "v_vestuario",
    momento: "verano",
    tipo: "personaje",
    categoria: "dinero",
    titulo: "Hay que decidir el presupuesto de vestuario",
    texto: "",
    unicaVez: true,
    opciones: [
      {
        id: "caro",
        titulo: "Tirar la casa por la ventana",
        subtitulo: "El atrezzo también puntúa",
        efectos: { puestaEnEscena: 2, dinero: -3 },
        flags: ["vestuario_caro"],
      },
      {
        id: "humilde",
        titulo: "Ahorrar en vestuario",
        subtitulo: "Que hable la letra, no el disfraz",
        efectos: { puestaEnEscena: -1, dinero: 2 },
        flags: ["vestuario_humilde"],
      },
    ],
  },
  {
    id: "v_patrocinador",
    momento: "verano",
    tipo: "personaje",
    categoria: "dinero",
    titulo: "Un patrocinador ofrece dinero a cambio de suavizar la crítica",
    texto: "",
    unicaVez: true,
    opciones: [
      {
        id: "aceptar",
        titulo: "Aceptar el dinero",
        subtitulo: "El carnaval también hay que pagarlo",
        efectos: { dinero: 3, popularidad: -1 },
        flags: ["acepto_patrocinio"],
      },
      {
        id: "rechazar",
        titulo: "Rechazar la oferta",
        subtitulo: "Aquí no se vende nadie",
        efectos: { dinero: -1, popularidad: 2 },
        flags: ["rechazo_patrocinio"],
      },
    ],
  },
  {
    id: "v_local",
    momento: "verano",
    tipo: "personaje",
    categoria: "dinero",
    titulo: "El local de ensayo sube el alquiler",
    texto: "",
    unicaVez: true,
    opciones: [
      {
        id: "nuevo",
        titulo: "Buscar otro local",
        subtitulo: "Donde se pueda pagar",
        efectos: { dinero: 1, cohesion: -1 },
        flags: ["local_nuevo"],
      },
      {
        id: "siempre",
        titulo: "Rascarse el bolsillo entre todos",
        subtitulo: "Aquí nació la agrupación",
        efectos: { dinero: -2, cohesion: 2 },
        flags: ["local_de_siempre"],
      },
    ],
  },
  {
    id: "v_historico",
    momento: "verano",
    tipo: "personaje",
    categoria: "grupo",
    titulo: "Un componente histórico quiere dejar el grupo",
    texto: "",
    unicaVez: true,
    opciones: [
      {
        id: "marchar",
        titulo: "Dejarlo marchar",
        subtitulo: "Cada uno tiene su momento",
        efectos: { cohesion: -1 },
        flags: ["historico_se_fue"],
      },
      {
        id: "quedarse",
        titulo: "Convencerlo de quedarse",
        subtitulo: "La agrupación es él también",
        efectos: { cohesion: 2 },
        flags: ["historico_se_queda"],
      },
    ],
  },
  {
    id: "v_fichaje",
    momento: "verano",
    tipo: "personaje",
    categoria: "grupo",
    titulo: "Te ofrecen fichar por otra agrupación más grande",
    texto: "",
    unicaVez: true,
    opciones: [
      {
        id: "fuera",
        titulo: "Cambiar de aires",
        subtitulo: "Buscar otro nivel",
        efectos: { popularidad: 2, cohesion: -2 },
        flags: ["fiche_fuera"],
      },
      {
        id: "fiel",
        titulo: "Ser fiel a los tuyos",
        subtitulo: "De aquí no me muevo",
        efectos: { cohesion: 2 },
        flags: ["me_quede"],
      },
    ],
  },
  {
    id: "v_ritmo",
    momento: "verano",
    tipo: "personaje",
    categoria: "grupo",
    titulo: "El carnaval te está comiendo la vida de casa",
    texto: "",
    unicaVez: true,
    opciones: [
      {
        id: "apretar",
        titulo: "Apretar hasta febrero",
        subtitulo: "Ya descansaré en marzo",
        efectos: { letra: 1, musica: 1, cohesion: -1 },
        flags: ["todo_al_carnaval"],
      },
      {
        id: "bajar",
        titulo: "Bajar el ritmo de ensayos",
        subtitulo: "Hay vida fuera del Falla",
        efectos: { cohesion: 1, musica: -1 },
        flags: ["pie_en_casa"],
      },
    ],
  },
  {
    id: "v_plantilla",
    momento: "verano",
    tipo: "personaje",
    categoria: "grupo",
    titulo: "Hay que cerrar la plantilla del año",
    texto: "",
    unicaVez: true,
    opciones: [
      {
        id: "joven",
        titulo: "Apostar por la cantera",
        subtitulo: "Gente joven con hambre",
        efectos: { cohesion: 2, musica: -1, dinero: 1 },
        flags: ["plantilla_joven"],
      },
      {
        id: "veterana",
        titulo: "Fichar veteranos de garantía",
        subtitulo: "Lo seguro se paga",
        efectos: { musica: 2, dinero: -2 },
        flags: ["plantilla_veterana"],
      },
    ],
  },
  {
    id: "v_protagonismo",
    momento: "verano",
    tipo: "personaje",
    categoria: "grupo",
    titulo: "Un componente se ha hecho más conocido que tú dentro del grupo",
    texto: "",
    unicaVez: true,
    opciones: [
      {
        id: "galones",
        titulo: "Darle galones",
        subtitulo: "Si tira, que tire de todos",
        efectos: { popularidad: 2, cohesion: 1, letra: -1 },
        flags: ["reparto_protagonismo"],
      },
      {
        id: "firma",
        titulo: "Marcar quién firma aquí",
        subtitulo: "El grupo tiene un autor",
        efectos: { letra: 1, cohesion: -2 },
        flags: ["autoridad_marcada"],
      },
    ],
  },
  {
    id: "v_filtracion",
    momento: "verano",
    tipo: "personaje",
    categoria: "grupo",
    titulo: "Alguien graba un ensayo y lo sube a redes antes de tiempo",
    texto: "",
    unicaVez: true,
    opciones: [
      {
        id: "aprovechar",
        titulo: "Aprovechar el ruido",
        subtitulo: "Publicidad gratis",
        efectos: { popularidad: 2, cohesion: -1 },
        flags: ["filtracion_aprovechada"],
      },
      {
        id: "cerrar",
        titulo: "Cerrar el ensayo a cal y canto",
        subtitulo: "Aquí no entra nadie",
        efectos: { cohesion: 1, popularidad: -1 },
        flags: ["ensayo_cerrado"],
      },
    ],
  },
  {
    id: "v_grupo_consagrado",
    momento: "verano",
    tipo: "personaje",
    categoria: "carrera",
    titulo:
      "Llevas muchos años con tu grupo de amigos y un grupo consagrado y puntero te ofrece ser su autor",
    texto: "",
    unicaVez: true,
    opciones: [
      {
        id: "pena",
        titulo: "Fiel a la peña",
        subtitulo: "Con estos empecé y con estos sigo",
        efectos: { cohesion: 2, popularidad: -1 },
        flags: ["rechace_grupo_consagrado"],
      },
      {
        id: "elite",
        titulo: "Firmar por el grupo consagrado",
        subtitulo: "Jugar en la élite",
        efectos: { popularidad: 2, letra: 1, cohesion: -2 },
        flags: ["autor_grupo_consagrado"],
      },
    ],
  },
  {
    id: "v_enfado_coac",
    momento: "verano",
    tipo: "personaje",
    categoria: "concurso",
    titulo:
      "Te enfadas con el COAC por unos resultados que consideras injustos",
    texto: "",
    unicaVez: true,
    opciones: [
      {
        id: "calle",
        titulo: "Pa la calle",
        subtitulo:
          "No concursas: sacas una agrupación callejera para tomar aire",
        efectos: { popularidad: 1, cohesion: 2, dinero: -1 },
        flags: ["ano_callejero"],
        saltaCOAC: true,
      },
      {
        id: "gira",
        titulo: "Gira por España",
        subtitulo: "No concursas, pero recorréis teatros de todo el país",
        efectos: { dinero: 3, popularidad: 1, cohesion: -1 },
        flags: ["ano_de_gira"],
        saltaCOAC: true,
      },
      {
        id: "concursar",
        titulo: "Me gusta concursar",
        subtitulo: "Vas al COAC con un pasodoble al trato del jurado",
        efectos: { letra: 2, popularidad: 2, cohesion: -1 },
        flags: ["pasodoble_al_jurado"],
      },
    ],
  },
]
